spring:
  datasource:
    url: jdbc:mysql://124.221.127.36:3306/springbootjlvpC?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: NJUseLong995

# similarity-service-url
similarity-service:
  url: http://124.221.127.36:8082