# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8080
    servlet:
        context-path: /collect

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
    servlet:
      multipart:
        max-file-size: 1024MB
        max-request-size: 1024MB
    resources:
      static-locations: classpath:static/,file:static/

# mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.po
  configuration:
    cache-enabled: false
  global-config:
    db-config:
      # 添加自增策略
      id-type: auto

# similarity-service-url
similarity-service:
  url: http://127.0.0.1:5000
